import { CuratedVideo } from '../types';

export const SEED_CURATED_VIDEOS: CuratedVideo[] = [
  {
    id: 'seed-yt-1',
    provider: 'youtube',
    providerVideoId: 'dQw4w9WgXcQ',
    title: 'Rick Astley - Never Gonna Give You Up (Official Music Video)',
    description: 'Classic iconic music video curated for family entertainment.',
    thumbnailUrl: 'https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
    duration: '3:33',
    category: 'Music',
    tags: ['Music', 'Classic', 'Family Picks'],
    safetyStatus: 'approved',
    addedAt: new Date().toISOString(),
  },
  {
    id: 'seed-yt-2',
    provider: 'youtube',
    providerVideoId: 'lFm4y5kU6N0',
    title: 'Satisfying Kinetic Sand Cutting & ASMR Relaxation',
    description: 'Calming and relaxing kinetic sand art demonstration.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    duration: '4:15',
    category: 'Relaxation',
    tags: ['ASMR', 'Relaxation', 'Shorts', 'Trending Shorts'],
    safetyStatus: 'approved',
    addedAt: new Date().toISOString(),
  },
  {
    id: 'seed-yt-3',
    provider: 'youtube',
    providerVideoId: 'L_LUpnjgPso',
    title: 'How Spacecraft Land on Mars - JPL Animation',
    description: 'NASA Jet Propulsion Laboratory educational animation of Mars rover landing.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
    duration: '5:42',
    category: 'Educational',
    tags: ['Space', 'Science', 'Educational'],
    safetyStatus: 'approved',
    addedAt: new Date().toISOString(),
  },
  {
    id: 'seed-yt-4',
    provider: 'youtube',
    providerVideoId: 'hFZFjoX2cGg',
    title: 'Mark Rober - World Largest Elephant Toothpaste Experiment',
    description: 'Fun and mind-blowing science experiment demonstrated by former NASA engineer Mark Rober.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=600&q=80',
    duration: '11:24',
    category: 'Educational',
    tags: ['Science', 'Experiments', 'Educational'],
    safetyStatus: 'approved',
    addedAt: new Date().toISOString(),
  },
  {
    id: 'seed-yt-5',
    provider: 'youtube',
    providerVideoId: 'jfKfPfyJRdk',
    title: 'Lofi Hip Hop Radio - Beats to Relax/Study to',
    description: 'Continuous smooth beats stream for studying and chill ambiance.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80',
    duration: 'LIVE',
    category: 'Music',
    tags: ['Lofi', 'Music', 'Twitch Live'],
    safetyStatus: 'approved',
    addedAt: new Date().toISOString(),
    isLive: true,
  },
  {
    id: 'seed-yt-6',
    provider: 'youtube',
    providerVideoId: 'r5P-fpy2D7w',
    title: 'BBC Earth - Planet Earth 4K Ultra HD Wildlife Highlights',
    description: 'Spectacular 4K nature and wildlife compilation from BBC Earth.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    duration: '15:20',
    category: 'Documentary',
    tags: ['Nature', 'Wildlife', 'Documentary'],
    safetyStatus: 'approved',
    addedAt: new Date().toISOString(),
  },
  {
    id: 'seed-yt-7',
    provider: 'youtube',
    providerVideoId: '9Hn2A8VjF40',
    title: 'TED-Ed - How Do Painkillers Work?',
    description: 'Educational animated explanation of human biology and pharmacology.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?auto=format&fit=crop&w=600&q=80',
    duration: '5:08',
    category: 'Educational',
    tags: ['TED-Ed', 'Science', 'Educational'],
    safetyStatus: 'approved',
    addedAt: new Date().toISOString(),
  },
  {
    id: 'seed-yt-8',
    provider: 'youtube',
    providerVideoId: 'gT0LhB-N028',
    title: 'Dude Perfect - Real Life Water Bottle Flip Trick Shots',
    description: 'Clean comedy and trick shot entertainment from Dude Perfect.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=600&q=80',
    duration: '7:40',
    category: 'Comedy',
    tags: ['Sports', 'Comedy', 'Family Picks'],
    safetyStatus: 'approved',
    addedAt: new Date().toISOString(),
  },
  {
    id: 'seed-yt-9',
    provider: 'youtube',
    providerVideoId: 'fE30Jj1_oQ0',
    title: 'Storyline Online - A Bad Case of Stripes read by Sean Astin',
    description: 'Childrens storybook reading session presented by SAG-AFTRA Foundation.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
    duration: '12:15',
    category: 'Storytime',
    tags: ['Reading', 'Storytime', 'Educational'],
    safetyStatus: 'approved',
    addedAt: new Date().toISOString(),
  },
  {
    id: 'seed-yt-10',
    provider: 'youtube',
    providerVideoId: 'W0LHTWG-UmQ',
    title: 'Studio Ghibli Relaxing Piano Medley for Sleep & Study',
    description: 'Beautiful orchestral piano renditions of Ghibli classics.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=600&q=80',
    duration: '45:00',
    category: 'Music',
    tags: ['Anime', 'Piano', 'Music'],
    safetyStatus: 'approved',
    addedAt: new Date().toISOString(),
  },
  {
    id: 'seed-vimeo-1',
    provider: 'vimeo',
    providerVideoId: '76979871',
    title: 'The Mountain - Award Winning Short Film',
    description: 'Cinematic landscape cinematography capturing breathtaking mountain ranges.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=80',
    duration: '3:05',
    category: 'Vimeo Films',
    tags: ['Film', 'Shorts', 'Vimeo Films'],
    safetyStatus: 'approved',
    addedAt: new Date().toISOString(),
  },
  {
    id: 'seed-vimeo-2',
    provider: 'vimeo',
    providerVideoId: '22439234',
    title: 'Arctic Light - Breathtaking Aurora Borealis in Norway',
    description: 'High definition timelapse film of northern lights over frozen fjords.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?auto=format&fit=crop&w=600&q=80',
    duration: '4:30',
    category: 'Documentary',
    tags: ['Nature', 'Timelapse', 'Vimeo Films'],
    safetyStatus: 'approved',
    addedAt: new Date().toISOString(),
  },
  {
    id: 'seed-dm-1',
    provider: 'dailymotion',
    providerVideoId: 'x8my011',
    title: 'The Beauty of Origami - Japanese Paper Craft Documentary',
    description: 'Exploring traditional paper folding techniques and geometric art.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    duration: '6:12',
    category: 'Educational',
    tags: ['Craft', 'Art', 'Educational'],
    safetyStatus: 'approved',
    addedAt: new Date().toISOString(),
  },
  {
    id: 'seed-dm-2',
    provider: 'dailymotion',
    providerVideoId: 'x7w8901',
    title: 'Wonders of the Ocean Deep - Marine Life Special',
    description: 'Exploring bioluminescent creatures of the deep ocean trench.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
    duration: '8:45',
    category: 'Documentary',
    tags: ['Ocean', 'Documentary', 'Science'],
    safetyStatus: 'approved',
    addedAt: new Date().toISOString(),
  },
  {
    id: 'seed-twitch-1',
    provider: 'twitch',
    providerVideoId: 'bobross',
    title: 'The Joy of Painting with Bob Ross - 24/7 Official Stream',
    description: 'Relaxing painting stream with Bob Ross creating happy little trees.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80',
    duration: 'LIVE',
    category: 'Twitch Live',
    tags: ['Art', 'Relaxation', 'Twitch Live'],
    safetyStatus: 'approved',
    addedAt: new Date().toISOString(),
    isLive: true,
  },
  {
    id: 'seed-twitch-2',
    provider: 'twitch',
    providerVideoId: 'monstercat',
    title: 'Monstercat 24/7 Electronic Music Radio Stream',
    description: 'Live family-friendly electronic music broadcast.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=600&q=80',
    duration: 'LIVE',
    category: 'Twitch Live',
    tags: ['Music', 'Live', 'Twitch Live'],
    safetyStatus: 'approved',
    addedAt: new Date().toISOString(),
    isLive: true,
  },
];
